// GENERATED by tools/build-help.mjs from USER_GUIDE.md — do not edit.
export const GUIDE_SECTIONS = [
 {
  "slug": "part-1-requesting-equipment-no-login",
  "title": "Part 1: Requesting equipment (no login)",
  "level": 2,
  "html": "<p>Anyone in the company can ask IT for hardware. You do not need an ITrack account.</p>",
  "text": "Anyone in the company can ask IT for hardware. You do not need an ITrack account."
 },
 {
  "slug": "request-equipment",
  "title": "Request equipment",
  "level": 3,
  "html": "<ol><li>Open ITrack and choose <strong>I Need Equipment</strong>.</li><li>Fill in <strong>Your name</strong> and <strong>Department</strong>. Use your name as it appears in the staff list; IT uses it to match the request to you.</li><li>Under <strong>What do you need?</strong> pick the type of item (laptop, monitor, printer…).</li><li>Choose <strong>Normal</strong> or <strong>Urgent</strong>, and say <strong>Why do you need it?</strong>. A sentence or two helps IT decide quickly.</li><li>Optionally attach up to 4 photos, for example of a broken item. On a phone, <strong>Camera</strong> opens the camera directly.</li><li>Press <strong>Send request</strong>.</li></ol><p>You get a <strong>receipt</strong> with your request number. Press <strong>Download receipt</strong> to keep a PDF copy, and quote the number whenever you contact IT.</p><blockquote>The form is for hardware only. For software, email or account problems, contact IT directly.</blockquote><p>If the form says you have sent too many requests, wait an hour or call IT. Each name can send 5 requests an hour, to stop the form being flooded.</p>",
  "text": "Open ITrack and choose I Need Equipment . Fill in Your name and Department . Use your name as it appears in the staff list; IT uses it to match the request to you. Under What do you need? pick the type of item (laptop, monitor, printer…). Choose Normal or Urgent , and say Why do you need it? . A sentence or two helps IT decide quickly. Optionally attach up to 4 photos, for example of a broken item. On a phone, Camera opens the camera directly. Press Send request . You get a receipt with your request number. Press Download receipt to keep a PDF copy, and quote the number whenever you contact IT. The form is for hardware only. For software, email or account problems, contact IT directly. If the form says you have sent too many requests, wait an hour or call IT. Each name can send 5 requests an hour, to stop the form being flooded."
 },
 {
  "slug": "track-your-request",
  "title": "Track your request",
  "level": 3,
  "html": "<p>Choose <strong>Track this request</strong> on your receipt, or open <strong>Track your request</strong> from the request page, and type your request number. You will see the status, the dates, and whether the item has been delivered and its receipt confirmed.</p><table><thead><tr><th>Status</th><th>Meaning</th></tr></thead><tbody><tr><td>Requested</td><td>IT has your request and has not acted on it yet.</td></tr><tr><td>Approved</td><td>IT has agreed to supply the item.</td></tr><tr><td>Allocated</td><td>A specific item has been set aside for you.</td></tr><tr><td>Delivered</td><td>The item has been handed over.</td></tr><tr><td>Rejected / Cancelled</td><td>The request is closed. Contact IT if you need to know why.</td></tr></tbody></table>",
  "text": "Choose Track this request on your receipt, or open Track your request from the request page, and type your request number. You will see the status, the dates, and whether the item has been delivered and its receipt confirmed. Status Meaning Requested IT has your request and has not acted on it yet. Approved IT has agreed to supply the item. Allocated A specific item has been set aside for you. Delivered The item has been handed over. Rejected / Cancelled The request is closed. Contact IT if you need to know why."
 },
 {
  "slug": "confirm-you-received-an-item",
  "title": "Confirm you received an item",
  "level": 3,
  "html": "<p>When IT issues an item to you, you get an email from the IT helpdesk titled <strong>&quot;… has been issued to you&quot;</strong>. Check the item, then press <strong>Confirm receipt</strong> in the email. ITrack asks for your <strong>ID number</strong> as a signature, then records that you received it.</p><p>The link works once and expires after 7 days. Opening it does nothing on its own; only pressing the button records anything.</p>",
  "text": "When IT issues an item to you, you get an email from the IT helpdesk titled \"… has been issued to you\" . Check the item, then press Confirm receipt in the email. ITrack asks for your ID number as a signature, then records that you received it. The link works once and expires after 7 days. Opening it does nothing on its own; only pressing the button records anything."
 },
 {
  "slug": "part-2-for-it-officers",
  "title": "Part 2: For IT officers",
  "level": 2,
  "html": "",
  "text": ""
 },
 {
  "slug": "signing-in",
  "title": "Signing in",
  "level": 3,
  "html": "<p>Choose <strong>IT Department</strong>, then sign in with your <strong>ID number</strong> and password. There is no &quot;forgot password&quot; email: if you forget it, ask an administrator to set a new one.</p><p>Press <strong>Ctrl K</strong> (or <strong>Search</strong> in the header) to jump to any page, asset or person by typing.</p>",
  "text": "Choose IT Department , then sign in with your ID number and password. There is no \"forgot password\" email: if you forget it, ask an administrator to set a new one. Press Ctrl K (or Search in the header) to jump to any page, asset or person by typing."
 },
 {
  "slug": "asset-register",
  "title": "Asset Register",
  "level": 3,
  "html": "<p>The home page lists every IT item the company owns, live from the database.</p><ul><li>The <strong>cards</strong> at the top count assets by status. Press one to filter by it.</li><li><strong>Search</strong> finds tag, serial, make, model or holder. <strong>Filters</strong> narrows by type, status, department, location and warranty.</li><li><strong>Register asset</strong> adds a new item. <strong>Open / Update</strong> (or a row) shows the full record: details, photos, current and past holders, and the history of every change.</li><li>Tick rows to <strong>Change status…</strong> or delete several at once. Deleting needs you to <strong>press and hold</strong> the button, so it cannot happen by a stray click.</li><li><strong>Export CSV</strong> exports the ticked rows, or every row matching the filters if none are ticked.</li></ul><p>Statuses are <strong>In stock</strong>, <strong>Assigned</strong>, <strong>Loaned</strong>, <strong>In repair</strong>, <strong>Retired</strong> and <strong>Lost/Stolen</strong>. Assigned and Loaned are set by Allocate / Return, not by hand.</p>",
  "text": "The home page lists every IT item the company owns, live from the database. The cards at the top count assets by status. Press one to filter by it. Search finds tag, serial, make, model or holder. Filters narrows by type, status, department, location and warranty. Register asset adds a new item. Open / Update (or a row) shows the full record: details, photos, current and past holders, and the history of every change. Tick rows to Change status… or delete several at once. Deleting needs you to press and hold the button, so it cannot happen by a stray click. Export CSV exports the ticked rows, or every row matching the filters if none are ticked. Statuses are In stock , Assigned , Loaned , In repair , Retired and Lost/Stolen . Assigned and Loaned are set by Allocate / Return, not by hand."
 },
 {
  "slug": "allocate-return",
  "title": "Allocate / Return",
  "level": 3,
  "html": "<p>Every hand-over and every return goes through this page, so the register always knows who holds what.</p><p><strong>Check out</strong> (issue an item):</p><ol><li><strong>Asset to issue</strong>: search by tag, serial, make or model. Only items that are In stock appear.</li><li><strong>Holder</strong>: pick a <strong>Person</strong>, or a <strong>Location</strong> for shared equipment.</li><li><strong>Details</strong>: the issue date, the <strong>Condition out</strong> (e.g. &quot;with charger and bag&quot;), and optionally the request it fulfils. Setting <strong>Due back</strong> makes it a loan.</li><li>Press <strong>Issue asset</strong> (or <strong>Loan asset</strong>).</li></ol><p>If the person has an email address in their staff record, they receive a handover email asking them to confirm receipt.</p><p><strong>Check in</strong> (take an item back): pick the <strong>Asset to return</strong>, set the <strong>Returned on</strong> date and <strong>Condition in</strong>, and choose where it <strong>Goes back to</strong>: In stock, or In repair.</p><p>Two people cannot issue the same item at once; the second gets a clear message.</p>",
  "text": "Every hand-over and every return goes through this page, so the register always knows who holds what. Check out (issue an item): Asset to issue : search by tag, serial, make or model. Only items that are In stock appear. Holder : pick a Person , or a Location for shared equipment. Details : the issue date, the Condition out (e.g. \"with charger and bag\"), and optionally the request it fulfils. Setting Due back makes it a loan. Press Issue asset (or Loan asset ). If the person has an email address in their staff record, they receive a handover email asking them to confirm receipt. Check in (take an item back): pick the Asset to return , set the Returned on date and Condition in , and choose where it Goes back to : In stock, or In repair. Two people cannot issue the same item at once; the second gets a clear message."
 },
 {
  "slug": "equipment-request",
  "title": "Equipment Request",
  "level": 3,
  "html": "<p>The queue of every open request, from the public form and from staff.</p><ul><li><strong>New equipment request</strong> raises one on someone's behalf.</li><li><strong>Set status…</strong> moves a request on: Requested → Approved → Allocated → Delivered. Setting Delivered records the date.</li><li><strong>Assign handler…</strong> makes an officer responsible for it.</li><li><strong>Allocate</strong> opens Allocate / Return with the request already filled in.</li><li><strong>Ask for release</strong> sends the request to the asset custodian for a release decision (see <a href=\"/help/#release-decisions\">Release decisions</a>).</li><li>Tick <strong>Show delivered and closed</strong> to see finished requests.</li></ul><p><strong>From your inbox.</strong> IT managers receive an email for each new request. It can carry <strong>Allocate</strong> buttons (in-stock items of the right type) and <strong>Assign</strong> buttons (officers). Pressing one opens a page that shows exactly what will happen and asks you to <strong>Confirm</strong>. Nothing happens until you press it, and each email link works once, for 7 days.</p>",
  "text": "The queue of every open request, from the public form and from staff. New equipment request raises one on someone's behalf. Set status… moves a request on: Requested → Approved → Allocated → Delivered. Setting Delivered records the date. Assign handler… makes an officer responsible for it. Allocate opens Allocate / Return with the request already filled in. Ask for release sends the request to the asset custodian for a release decision (see Release decisions ). Tick Show delivered and closed to see finished requests. From your inbox. IT managers receive an email for each new request. It can carry Allocate buttons (in-stock items of the right type) and Assign buttons (officers). Pressing one opens a page that shows exactly what will happen and asks you to Confirm . Nothing happens until you press it, and each email link works once, for 7 days."
 },
 {
  "slug": "warranty-and-refresh",
  "title": "Warranty & Refresh",
  "level": 3,
  "html": "<p>Four lists: warranties <strong>Expired</strong>, warranties <strong>expiring</strong> in the next 30, 60 or 90 days, <strong>Refresh overdue</strong>, and <strong>Refresh due this year</strong>. Each row opens the asset. Export to CSV or Excel for purchasing.</p><p>The <strong>bell</strong> in the header shows the same items, so the two never disagree.</p>",
  "text": "Four lists: warranties Expired , warranties expiring in the next 30, 60 or 90 days, Refresh overdue , and Refresh due this year . Each row opens the asset. Export to CSV or Excel for purchasing. The bell in the header shows the same items, so the two never disagree."
 },
 {
  "slug": "analytics",
  "title": "Analytics",
  "level": 3,
  "html": "<p>Charts of the active assets: by type, status and department, age, purchases per month, warranties ending per quarter, and how often items change hands. Under each chart, <strong>Show as table</strong> gives the figures.</p>",
  "text": "Charts of the active assets: by type, status and department, age, purchases per month, warranties ending per quarter, and how often items change hands. Under each chart, Show as table gives the figures."
 },
 {
  "slug": "asset-history",
  "title": "Asset History",
  "level": 3,
  "html": "<p>Look up everything that ever happened to an item, including deleted ones: every holder with condition notes, every change, and every request it was allocated against.</p><p>Search by tag, serial, make or model. Use <code>*</code> as a wildcard: <code>IT-02*</code> finds every tag starting IT-02; <code>*</code> on its own lists everything.</p>",
  "text": "Look up everything that ever happened to an item, including deleted ones: every holder with condition notes, every change, and every request it was allocated against. Search by tag, serial, make or model. Use * as a wildcard: IT-02* finds every tag starting IT-02; * on its own lists everything."
 },
 {
  "slug": "part-3-for-approvers-managers-and-administrators",
  "title": "Part 3: For approvers, managers and administrators",
  "level": 2,
  "html": "",
  "text": ""
 },
 {
  "slug": "access-levels",
  "title": "Access levels",
  "level": 3,
  "html": "<table><thead><tr><th>Access level</th><th>Who</th><th>Can do</th></tr></thead><tbody><tr><td>Officer (default)</td><td>IT officers</td><td>Register, Allocate / Return, Equipment Request, Asset History.</td></tr><tr><td>Approver</td><td>Asset custodian</td><td>Everything an officer can, plus <strong>approve or reject a release</strong>.</td></tr><tr><td>Viewer</td><td>Supervisors, auditors</td><td>Read everything operational, change nothing. May still raise a request.</td></tr><tr><td>Admin</td><td>IT manager</td><td>Everything except release decisions, plus Asset Value, Data Management, User Management and Change Log.</td></tr><tr><td>Super admin</td><td>IT HOD</td><td>Everything, including release decisions.</td></tr></tbody></table><p>The access level is not the job title. Both are set in User Management.</p>",
  "text": "Access level Who Can do Officer (default) IT officers Register, Allocate / Return, Equipment Request, Asset History. Approver Asset custodian Everything an officer can, plus approve or reject a release . Viewer Supervisors, auditors Read everything operational, change nothing. May still raise a request. Admin IT manager Everything except release decisions, plus Asset Value, Data Management, User Management and Change Log. Super admin IT HOD Everything, including release decisions. The access level is not the job title. Both are set in User Management."
 },
 {
  "slug": "release-decisions",
  "title": "Release decisions",
  "level": 3,
  "html": "<p>When an officer presses <strong>Ask for release</strong>, the custodian receives an email, and the request appears under <strong>Equipment Request → Approvals</strong> with a count on the menu. If something is waiting when an approver signs in, ITrack opens that view for them.</p><p>To decide, add remarks (required to reject), type <strong>your own ID number</strong> as a signature, and press <strong>Approve release</strong> or <strong>Reject</strong>. The requester's manager and IT are emailed the outcome. The decision is only ever made in ITrack, never from an email, so it always carries a signed-in name.</p>",
  "text": "When an officer presses Ask for release , the custodian receives an email, and the request appears under Equipment Request → Approvals with a count on the menu. If something is waiting when an approver signs in, ITrack opens that view for them. To decide, add remarks (required to reject), type your own ID number as a signature, and press Approve release or Reject . The requester's manager and IT are emailed the outcome. The decision is only ever made in ITrack, never from an email, so it always carries a signed-in name."
 },
 {
  "slug": "asset-value",
  "title": "Asset Value",
  "level": 3,
  "html": "<p><em>Administrators only.</em> Purchase cost and today's book value by department and asset type, purchases per month, and value at year end. Book value is straight-line depreciation over the item's refresh period. Items with no recorded cost are counted separately so the totals are not misleading.</p>",
  "text": "Administrators only. Purchase cost and today's book value by department and asset type, purchases per month, and value at year end. Book value is straight-line depreciation over the item's refresh period. Items with no recorded cost are counted separately so the totals are not misleading."
 },
 {
  "slug": "data-management",
  "title": "Data Management",
  "level": 3,
  "html": "<p><em>Administrators only.</em> The lists behind the rest of ITrack: <strong>Locations</strong>, <strong>Vendors</strong>, <strong>Staff</strong> records and <strong>Notify Emails</strong>.</p><ul><li><strong>Notify Emails</strong> decides who is emailed, by purpose: <em>New equipment request</em>, <em>Release waiting for decision</em> and <em>Release decided</em>. Being an administrator does not add you to any list; add your address for the purposes you want.</li><li><strong>Notify Health</strong> shows the last 7 days of email: sent, failed, and why. &quot;Accepted by mail provider&quot; means Microsoft accepted the message, not that it reached the inbox. To trace one, use <strong>Message trace</strong> in the Exchange admin centre.</li></ul><p>A staff record's <strong>Eligible</strong> setting decides whether they can be made a request handler. <strong>Use the department rule</strong> means &quot;yes if their department is IT&quot;.</p>",
  "text": "Administrators only. The lists behind the rest of ITrack: Locations , Vendors , Staff records and Notify Emails . Notify Emails decides who is emailed, by purpose: New equipment request , Release waiting for decision and Release decided . Being an administrator does not add you to any list; add your address for the purposes you want. Notify Health shows the last 7 days of email: sent, failed, and why. \"Accepted by mail provider\" means Microsoft accepted the message, not that it reached the inbox. To trace one, use Message trace in the Exchange admin centre. A staff record's Eligible setting decides whether they can be made a request handler. Use the department rule means \"yes if their department is IT\"."
 },
 {
  "slug": "user-management",
  "title": "User Management",
  "level": 3,
  "html": "<p><em>Administrators only.</em> Logins and staff records on one screen.</p><ul><li><strong>Add user</strong> creates the login and the staff record together. The ID number is the login; ITrack shows the sign-in address it generates before you save.</li><li>Give an <strong>email address</strong> if the person should get handover emails.</li><li><strong>Access level</strong> and <strong>Job title</strong> are separate. See <a href=\"/help/#access-levels\">Access levels</a>.</li><li><strong>Set password</strong> gives someone a new password. Tell them in person; there is no reset email.</li><li><strong>Disable</strong>, never delete. A disabled account cannot sign in, keeps its history, and can be <strong>Re-enabled</strong>.</li></ul><p>You cannot remove your own admin access or disable yourself, and the last active administrator cannot be demoted or disabled.</p>",
  "text": "Administrators only. Logins and staff records on one screen. Add user creates the login and the staff record together. The ID number is the login; ITrack shows the sign-in address it generates before you save. Give an email address if the person should get handover emails. Access level and Job title are separate. See Access levels . Set password gives someone a new password. Tell them in person; there is no reset email. Disable , never delete. A disabled account cannot sign in, keeps its history, and can be Re-enabled . You cannot remove your own admin access or disable yourself, and the last active administrator cannot be demoted or disabled."
 },
 {
  "slug": "change-log",
  "title": "Change Log",
  "level": 3,
  "html": "<p><em>Administrators only.</em> One read-only feed of sign-ins, account changes and every change to an asset, newest first. Filter by category, person and date. Nothing in it can be edited or deleted.</p>",
  "text": "Administrators only. One read-only feed of sign-ins, account changes and every change to an asset, newest first. Filter by category, person and date. Nothing in it can be edited or deleted."
 },
 {
  "slug": "sign-in-briefing",
  "title": "Sign-in briefing",
  "level": 3,
  "html": "<p>Administrators see a short <strong>Needs attention</strong> summary once per sign-in: expiring warranties, overdue refreshes, and requests left untouched. The bell keeps the same list for the rest of the session.</p>",
  "text": "Administrators see a short Needs attention summary once per sign-in: expiring warranties, overdue refreshes, and requests left untouched. The bell keeps the same list for the rest of the session."
 },
 {
  "slug": "common-questions",
  "title": "Common questions",
  "level": 2,
  "html": "",
  "text": ""
 },
 {
  "slug": "i-forgot-my-password",
  "title": "I forgot my password",
  "level": 3,
  "html": "<p>Ask an ITrack administrator to set a new one in User Management. There is no reset email, because sign-in uses your ID number, not an email address.</p>",
  "text": "Ask an ITrack administrator to set a new one in User Management. There is no reset email, because sign-in uses your ID number, not an email address."
 },
 {
  "slug": "the-item-i-want-to-issue-is-not-in-the-list",
  "title": "The item I want to issue is not in the list",
  "level": 3,
  "html": "<p>Only <strong>In stock</strong> items can be issued. Check its status on the Asset Register; if it is still held by someone, check it in first.</p>",
  "text": "Only In stock items can be issued. Check its status on the Asset Register; if it is still held by someone, check it in first."
 },
 {
  "slug": "someone-did-not-get-the-handover-email",
  "title": "Someone did not get the handover email",
  "level": 3,
  "html": "<p>Their staff record needs a real email address (User Management or Data Management → Staff). No email is sent when you issue an item to yourself.</p>",
  "text": "Their staff record needs a real email address (User Management or Data Management → Staff). No email is sent when you issue an item to yourself."
 },
 {
  "slug": "an-email-button-says-the-link-was-already-used-or-has-expired",
  "title": "An email button says the link was already used or has expired",
  "level": 3,
  "html": "<p>Each link works once and for 7 days. Do the same thing in ITrack instead: the email's <strong>Open in ITrack</strong> button takes you to the queue.</p>",
  "text": "Each link works once and for 7 days. Do the same thing in ITrack instead: the email's Open in ITrack button takes you to the queue."
 },
 {
  "slug": "is-email-guaranteed",
  "title": "Is email guaranteed?",
  "level": 3,
  "html": "<p>No. Email is best effort: a request is always saved, even when the email cannot be sent. Check <strong>Notify Health</strong> if mail seems to be missing, and do not put confidential information in a request.</p>",
  "text": "No. Email is best effort: a request is always saved, even when the email cannot be sent. Check Notify Health if mail seems to be missing, and do not put confidential information in a request."
 },
 {
  "slug": "who-to-contact",
  "title": "Who to contact",
  "level": 2,
  "html": "<p>For help with ITrack, a forgotten password or a new account, contact the IT Department (IT helpdesk, <code>helpdesk@tomypak.com.my</code>). Quote the request number or asset tag if you have one.</p>",
  "text": "For help with ITrack, a forgotten password or a new account, contact the IT Department (IT helpdesk, helpdesk@tomypak.com.my ). Quote the request number or asset tag if you have one."
 }
];
