// tools/build-help.mjs — compiles USER_GUIDE.md into app/help/guideContent.js
// at build time (run by `prebuild`). The output is COMMITTED, because prebuild
// does not run before `next dev`. No Markdown renderer ships to the client:
// there is no server, Apache serves .md without a content type, and an
// installed PWA must work offline.
//
// Every ## and ### heading starts a section { slug, title, level, html, text }.
// Slugs are a CONTRACT: <HelpLink section="..."> points at them, so renaming a
// heading breaks those links. tools/check-help.mjs asserts they all resolve.
//
// The converter handles only what USER_GUIDE.md uses: headings, paragraphs,
// - and 1. lists, > notes, | tables, **bold**, _italic_, `code`, [links](url).
// ponytail: screenshots (guideImages.js, lazy data: URIs) skipped until the
// guide has screenshots to embed.
import fs from "node:fs";
import { pathToFileURL } from "node:url";

const OUT = "app/help/guideContent.js";

export const slugify = (s) =>
  s.toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

// Inline markup, on already-escaped text. Code spans first so their contents
// are not read as bold or links.
function inline(s) {
  const codes = [];
  s = esc(s).replace(/`([^`]+)`/g, (_, c) => `\u0000${codes.push(c) - 1}\u0000`);
  s = s
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/(^|[\s(])_(.+?)_(?=[\s).,;:!?]|$)/g, "$1<em>$2</em>")
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (_, t, href) => `<a href="${href}">${t}</a>`);
  return s.replace(/\u0000(\d+)\u0000/g, (_, i) => `<code>${codes[i]}</code>`);
}

export function convert(md) {
  const sections = [];
  let cur = null;
  const lines = md.replace(/\r\n?/g, "\n").split("\n");
  for (let i = 0; i < lines.length; ) {
    const line = lines[i];
    const h = /^(#{1,3})\s+(.*)$/.exec(line);
    if (h) {
      i++;
      if (h[1].length === 1) continue; // the document title; the page has its own
      const title = h[2].trim();
      let slug = slugify(title);
      for (let n = 2; sections.some((s) => s.slug === slug); n++) slug = `${slugify(title)}-${n}`;
      sections.push((cur = { slug, title, level: h[1].length, html: "", text: "" }));
      continue;
    }
    if (!line.trim()) { i++; continue; }
    if (!cur) { i++; continue; } // text before the first section: the intro is not shown
    // Collect one block: consecutive lines of the same kind.
    const take = (re) => { const out = []; while (i < lines.length && re.test(lines[i])) out.push(lines[i++]); return out; };
    let html;
    if (/^\s*[-*] /.test(line)) {
      const items = take(/^\s*([-*] |\s{2,}\S)/).join("\n").split(/\n?^\s*[-*] /m).filter(Boolean);
      html = `<ul>${items.map((t) => `<li>${inline(t.replace(/\s*\n\s*/g, " "))}</li>`).join("")}</ul>`;
    } else if (/^\s*\d+\. /.test(line)) {
      const items = take(/^\s*(\d+\. |\s{2,}\S)/).join("\n").split(/\n?^\s*\d+\. /m).filter(Boolean);
      html = `<ol>${items.map((t) => `<li>${inline(t.replace(/\s*\n\s*/g, " "))}</li>`).join("")}</ol>`;
    } else if (/^>/.test(line)) {
      html = `<blockquote>${inline(take(/^>/).map((l) => l.replace(/^>\s?/, "")).join(" "))}</blockquote>`;
    } else if (/^\|/.test(line)) {
      const rows = take(/^\|/).map((l) => l.replace(/^\||\|\s*$/g, "").split("|").map((c) => c.trim()));
      const [head, , ...body] = rows; // row 2 is the |---| separator
      html = `<table><thead><tr>${head.map((c) => `<th>${inline(c)}</th>`).join("")}</tr></thead><tbody>` +
        body.map((r) => `<tr>${r.map((c) => `<td>${inline(c)}</td>`).join("")}</tr>`).join("") + "</tbody></table>";
    } else {
      html = `<p>${inline(take(/^(?!\s*$|#|\s*[-*] |\s*\d+\. |>|\|)/).join(" "))}</p>`;
    }
    cur.html += html;
    cur.text += " " + html.replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"');
  }
  for (const s of sections) s.text = s.text.replace(/\s+/g, " ").trim();
  return sections;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const sections = fs.existsSync("USER_GUIDE.md") ? convert(fs.readFileSync("USER_GUIDE.md", "utf8")) : [];
  fs.mkdirSync("app/help", { recursive: true });
  fs.writeFileSync(OUT, "// GENERATED by tools/build-help.mjs from USER_GUIDE.md — do not edit.\n" +
    `export const GUIDE_SECTIONS = ${JSON.stringify(sections, null, 1)};\n`);
  console.log(`build-help: ${sections.length} sections -> ${OUT}`);
}
