// tools/build-help.mjs — compiles USER_GUIDE.md into app/help/guideContent.js
// at build time (run by `prebuild`). The output is COMMITTED, because prebuild
// does not run before `next dev`. No Markdown renderer ships to the client:
// there is no server, Apache serves .md without a content type, and an
// installed PWA must work offline.
//
// ponytail: phase 2 stub — writes an empty guide until USER_GUIDE.md exists.
// The heading splitter and Markdown→HTML conversion arrive with /help (phase 8).
import fs from "node:fs";

const OUT = "app/help/guideContent.js";
if (!fs.existsSync("USER_GUIDE.md")) {
  fs.mkdirSync("app/help", { recursive: true });
  fs.writeFileSync(OUT, "// GENERATED by tools/build-help.mjs — do not edit.\nexport const GUIDE_SECTIONS = [];\n");
  console.log("build-help: no USER_GUIDE.md yet; wrote empty guide");
} else {
  throw new Error("build-help: USER_GUIDE.md found but the converter is not built yet (phase 8)");
}
